### ISSUE TITLE
Pre-generated

### ISSUE THREAD

**Issue by arthurwolf** [imrahil/smoothieware-webui#1]
Hey.

Would you mind adding to the repo a pre-generated version for each language ?
That way folks just have to download/paste to their SD card.
If/when done, I'll add instructions on how to use this on the Smoothie wiki, and ask the community to test it ( if that's fine with you ).

Cheers, and very nice project :)

**Comment by imrahil** [comment]
the idea behind languages is to use Transifex webservice (https://www.transifex.com/imrahil/smoothieware-webui/)
all translated strings are located in .po files and will be compiled into final JS app.

tommorow I should test new version on real Smoothieboard

**Comment by arthurwolf** [comment]
So are you saying the repo as-is can be used directly on a smoothieboard without running a program first ?

**Comment by imrahil** [comment]
nope. it's little bit more complicated... :) I wanted to use all fancy tools and it's probably over-complicated hehe

for languages you have to use grunt to extract strings to translate (from HTML) and then to compile .po files into translations.js file. PO files you can create using Transifex webservice.

All app is compiled into one app.js using gulp. CSS files should be compiled into one file too (I'll add it tommorow). Final version (as in dist.zip in repo) should be one css, one js, one svg for jogdial and one HTML file

**Comment by arthurwolf** [comment]
Awesome !

On Mon, Apr 11, 2016 at 11:06 PM, Jarek Szczepanski <
notifications@github.com> wrote:

> nope. it's little bit more complicated... :) I wanted to use all fancy
> tools and it's probably over-complicated hehe
> 
> for languages you have to use grunt to extract strings to translate (from
> HTML) and then to compile .po files into translations.js file. PO files you
> can create using Transifex webservice.
> 
> All app is compiled into one app.js using gulp. CSS files should be
> compiled into one file too (I'll add it tommorow). Final version (as in
> dist.zip in repo) should be one css, one js, one svg for jogdial and one
> HTML file
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/imrahil/smoothieware-webui/issues/1#issuecomment-208560494

## 

Courage et bonne humeur.

**Comment by imrahil** [comment]
one more thing for additional languages: contributors don't have to use grunt to extract, compile, etc, etc - all what they have to do is add languages and translate strings on Transifex platform. Then I will add these new translations into app and release final build.

**Comment by imrahil** [comment]
dist.zip = files ready for Smoothie's SD card are released - so fixed :)

**Comment by arthurwolf** [comment]
Thanks a lot for this ! I added it to http://smoothieware.github.io/Webif-pack , it's very very nice

**Comment by imrahil** [comment]
Awesome! thanks!
