### ISSUE TITLE
How to build dist.zip ?

### ISSUE THREAD

**Issue by luc-github** [imrahil/smoothieware-webui#2]
Hi I would like to port your great UI to work with the ESP8266 wifi module with smoothie board, everything is working natively but unfortunalty ESP file upload method is different  than smoothieware one, it use normal file transfert methode instead of put all in header (https://github.com/luc-github/ESP3D/issues/112).
I would like to modify the upload function present in your function.js but I cannot see the code in final package... 
So sorry for asking, but how to build the dist.zip with minified files and obviously less files ?

Thanks in advance

**Comment by imrahil** [comment]
Hi! sorry for late response!
function.js is old file from original web ui from Smoothieware

for current version upload is executed in fileController.js using ng-file-upload plugin

**Comment by luc-github** [comment]
ho, ok, thanks for the clarification, I was able to build the dist.zip on my own after trial/error

ok will check the other file then to do the modifications

Thanks again
