### ISSUE TITLE
why not limit output to index.html

### ISSUE THREAD

**Issue by luc-github** [imrahil/smoothieware-webui#4]
after minifing css and js why not embedded them in final single index.html to follow the same logic ?
seems gulp-smoosher do Inline css and js links with file contents

https://www.npmjs.com/package/gulp-smoosher

I am not very familiar with gulp but I plan to apply this to smoothieware-webui for esp8266 as webserver do not handle too many connnection at once, so having 1 file is good - and esp webserver is able to handle .gz file so at the end I have index.hml.gz file for only 11.38 KB which is small footprint
I currently do the concat by hand with the dist.zip files content - but I will try to add the ultimate files fusion using gulp-smoosher, let me know if you are interrested I could push a PR to your github once done

**Comment by imrahil** [comment]
Great idea. I will change gulpfile.js tommorow

**Comment by luc-github** [comment]
Cool - thank you
