### ISSUE TITLE
Cosmetic issue when lot of files in panel

### ISSUE THREAD

**Issue by luc-github** [imrahil/smoothieware-webui#6]
Hi,
If there are lot of files, the list overload the panel instead of resize him:
![image](https://cloud.githubusercontent.com/assets/8822552/20648333/126a27fc-b4a4-11e6-98ac-463297205953.png)
It is just cosmetic - no functional impact
The ui is the one from my fork for ESP8266 but yours has same behavior - I am still learning angular, so did not found the way to resize when list is updated may be you are aware

**Comment by luc-github** [comment]
The most simple solution is to update **style.css**  to create a class panel-scroll to not affect others panel :
```
panel-scroll {
    overflow-y: scroll;
}
```
and to add this class to **index.html** file list panel:
`<div class="panel-body panel-height panel-scroll ">`

like : https://github.com/luc-github/smoothieware-webui-for-ESP3D/commit/cf88dde2f9d8e8c588380a45893fb19656f513cf

I hope it helps

**Comment by imrahil** [comment]
PR is welcome :)

**Comment by luc-github** [comment]
Well as previously I proposed 2 times to do PR and you did yourself - I was guessed you do not take PR :)

Ok will do later
